#include "surguch_translator.hpp"

#include <QLocale>
#include <array>
#include <string_view>

namespace core {
constexpr std::array<std::string_view, 174> tag_names{
    "OID",           "expDate",
    "АдрМЖ",         "АдрМНФакт",
    "АдрРФ",         "АдрРег",
    "АдрСтрРег",     "АдрЭлПочт",
    "Безотзыв",      "ВерсФорм",
    "ВидДовер",      "ВнНомДовер",
    "ВнНомДоверN",   "ВнНомДоверПерв",
    "ВриоНот",       "ВыдДок",
    "Гражданство",   "ДатаВнРегДовер",
    "ДатаВремПодп",  "ДатаВыд",
    "ДатаВыдДовер",  "ДатаДок",
    "ДатаРожд",      "Довер",
    "Доверенность",  "Доверит",
    "ДоверитПерв",   "ДокНедеесп",
    "ДокПдтв",       "Документ",
    "Должность",     "ДопИдДовер",
    "ДопСвНотДовер", "ДрИнфСист",
    "ДрСпосВыд",     "ЕИОИП",
    "ЕИОУК",         "ЕИОФЛ",
    "ИННФЛ",         "ИННЮЛ",
    "ИПДовер",       "ИППерПолн",
    "ИдОгр",         "ИдФИАС",
    "ИдФайл",        "ИдФайлНО",
    "Имя",           "ИнОргДовер",
    "ИнПерПолн",     "ИнСвУдНадпис",
    "ИнСвед",        "КНД",
    "КПП",           "КемВыд",
    "КодВидДок",     "КодВыдДок",
    "КодЗначОгр",    "КодНО",
    "КодНОДейст",    "КодНПРег",
    "КодОгр",        "КодПолн",
    "КонтактТлф",    "ЛицоБезДов",
    "ЛьготаСум",     "МашПолн",
    "МестоДовер",    "МестоРожд",
    "МнПолн",        "НЗА",
    "НаимДокПдтв",   "НаимЗначОгр",
    "НаимИО",        "НаимИП",
    "НаимОгр",       "НаимОрг",
    "НаимПолн",      "НаимРегОрг",
    "НаимУчрДок",    "НапрДокДовЕПГУ",
    "НапрДокЗвлФНП", "НапрДокПовЕПГУ",
    "НапрДокПовФНП", "НомДовер",
    "НомДоверN",     "НомДоверПерв",
    "НомЕРН",        "НомРНДN",
    "НомРНДДовер",   "НомРНДПерв",
    "ОГРН",          "ОГРНИП",
    "ОгрСвПолн",     "ОписУслОт",
    "Отчество",      "ПередПолн",
    "Передов",       "ПодпИзобр",
    "ПодпРукопис",   "Пол",
    "ПолнЮЛ",        "ПрГражд",
    "ПрДеесп",       "ПрДовер",
    "ПрНалПередов",  "ПрНалРук",
    "ПрПерБезДов",   "ПрПередов",
    "ПрСовмПолн",    "ПрУтрПолн",
    "ПрЭлФорм",      "Пред",
    "РегНомНот",     "РегНомер",
    "Регион",        "РосОргДовер",
    "РосОргПерПолн", "СВЮЛ",
    "СНИЛС",         "СвДов",
    "СвДоверПерв",   "СвДоверит",
    "СвЗакПредРук",  "СвИП",
    "СвИнОрг",       "СвНотДейств",
    "СвНотУд",       "СвПервДовер",
    "СвПереДовер",   "СвПередПолн",
    "СвПередов",     "СвПолн",
    "СвПолучПолн",   "СвРосОрг",
    "СвРукОП",       "СвРукФил",
    "СвУдДок",       "СвУпПред",
    "СвФЛ",          "СвФил",
    "СвЮЛЕИО",       "СведИО",
    "СведИП",        "СведОрг",
    "СведРукоп",     "СведСист",
    "СведФЛ",        "СведФизЛ",
    "СведФилиал",    "СерНомДок",
    "СрокДейст",     "СтУчНД",
    "СтрРег",        "ТексЗначОгр",
    "ТекстПолн",     "ТипДоверит",
    "ТипПерПолн",    "ТипПолн",
    "ТипПред",       "УдЛичнФЛ",
    "УплНотДейст",   "УслОтзыва",
    "ФИАСАдрРФ",     "ФИО",
    "ФИОВриоНот",    "ФИОНотДейств",
    "ФИООтв",        "ФЛДовер",
    "ФЛПерПолн",     "Фамилия",
    "ФилПерПолн",    "ФормДовер",
    "ХешPDFДок",     "ХешПодп",
};
constexpr std::array<std::string_view, 174> rus_expl{
    "Внешний идентификатор объекта ЕСИА",
    "Дата истечения срока действия документа, удостоверяющего личность",
    "Адрес места жительства",
    "Адрес (место нахождения) на территории Российской Федерации",
    "Адрес в Российской Федерации",
    "Адрес юридического лица / филиала (обособленного подразделения) "
    "юридического лица в Российской Федерации",
    "Адрес юридического лица на территории государства, в котором оно "
    "зарегистрировано",
    "Адрес электронной почты",
    "Сведения о безотзывной доверенности",
    "Версия формата",
    "Вид доверенности",
    "Внутренний номер доверенности",
    "Внутренний номер доверенности, на основании которой осуществляется "
    "передоверие",
    "Внутренний номер первоначальной доверенности",
    "ВРИО нотариуса",
    "Наименование органа, выдавшего документ",
    "Гражданство",
    "Дата внутренней регистрации доверенности",
    "Дата и время подписи",
    "Дата выдачи документа",
    "Дата совершения (выдачи) доверенности",
    "Дата выдачи документа",
    "Дата рождения",
    "Доверенность",
    "Сведения о доверенности",
    "Сведения о доверителе",
    "Сведения о доверителе первоначальной доверенности",
    "Документ, подтверждающий недееспособность доверителя",
    "Документ, подтверждающий полномочия лица, действующего без доверенности",
    "Состав и структура документа",
    "Должность",
    "Дополнительный идентификатор доверенности",
    "Дополнительные сведения",
    "Способ выдачи электронного нотариального документа",
    "Иной способ выдачи",
    "Единоличным исполнительным органом выступает индивидуальный "
    "предприниматель",
    "Единоличным исполнительным органом выступает управляющая компания",
    "Единоличным исполнительным органом выступает физическое лицо",
    "ИНН физического лица",
    "ИНН иностранного юридического лица / филиала (аккредитованного "
    "представительства) иностранного юридического лица",
    "Сведения об индивидуальном предпринимателе",
    "Сведения об индивидуальном предпринимателе",
    "Порядковый номер ограничения",
    "Идентификатор адреса по ФИАС",
    "Идентификатор файла",
    "Идентификатор файла для представления интересов в налоговом органе",
    "Имя",
    "Сведения об иностранном юридическом лице",
    "Сведения о филиале (аккредитованном представительстве) иностранного "
    "юридического лица",
    "Иные сведения удостоверительной надписи",
    "Иные сведения",
    "Код формы по КНД",
    "КПП филиала (аккредитованного представительства) иностранного "
    "юридического лица",
    "Наименование органа, выдавшего документ",
    "Код вида документа",
    "Код подразделения органа, выдавшего документ",
    "Код значения для ограничения",
    "Код налогового органа, в который представляется доверенность",
    "Код налогового органа, в отношении которого действует доверенность",
    "Код налогоплательщика в стране регистрации (инкорпорации) или аналог",
    "Код ограничения",
    "Код полномочия",
    "Контактный телефон",
    "Сведения о лице (лицах), действующем (действующих) от имени юридического "
    "лица без доверенности",
    "Предоставленная льгота на сумму",
    "Сведения о машиночитаемом полномочии (машиночитаемых полномочиях)",
    "Место совершения доверенности",
    "Место рождения",
    "Мнемоника полномочия",
    "Номер записи об аккредитации",
    "Наименование документа",
    "Наименование значения для ограничения",
    "Наименование иностранного юридического лица / филиала (аккредитованного "
    "представительства) иностранного юридического лица",
    "Наименование индивидуального предпринимателя",
    "Наименование ограничения",
    "Наименование юридического лица / Наименование филиала (обособленного "
    "подразделения) юридического лица",
    "Наименование полномочия",
    "Наименование регистрирующего органа",
    "Наименование учредительного документа",
    "Направление сформированного электронного документа в ЛК доверителя на "
    "сайте ЕПГУ",
    "Направление сформированного электронного документа в ЛК заявителя на "
    "сайте ФНП",
    "Направление сформированного электронного документа в ЛК поверенного на "
    "сайте ЕПГУ",
    "Направление сформированного электронного документа в ЛК поверенного на "
    "сайте ФНП",
    "Единый регистрационный номер доверенности",
    "Единый регистрационный номер доверенности, на основании которой "
    "осуществляется передоверие",
    "Единый регистрационный номер первоначальной доверенности",
    "Номер записи единого регистра населения",
    "Регистрационный номер доверенности в реестре нотариальных действий, на "
    "основании которой осуществляется передоверие",
    "Регистрационный номер доверенности в реестре нотариальных действий",
    "Регистрационный номер первоначальной доверенности в реестре нотариальных "
    "действий",
    "ОГРН",
    "ОГРНИП",
    "Сведения об ограничении (ограничениях) к полномочию",
    "Описание условия отзыва безотзывной доверенности",
    "Отчество (при наличии)",
    "Сведения о лице, передавшем полномочия",
    "Передоверие",
    "Изображение подписи",
    "Рукописная подпись",
    "Пол физического лица",
    "Вид полномочий единоличного исполнительного органа",
    "Признак наличия гражданства",
    "Признак наличия полной гражданской дееспособности доверителя",
    "Признак доверенности",
    "Признак наличия доверенности, выданной в порядке передоверия",
    "Признак наличия рукоприкладчика",
    "Признак передоверия безотзывной доверенности",
    "Признак возможности оформления передоверия",
    "Признак совместного осуществления полномочий",
    "Признак утраты полномочий при передоверии",
    "Флаг обязательности элементов",
    "Сведения о представителе",
    "Регистрационный номер лица, сдавшего квалификационный экзамен в Минюсте",
    "Регистрационный номер в стране регистрации (инкорпорации)",
    "Субъект Российской Федерации",
    "Сведения о юридическом лице",
    "Сведения о юридическом лице",
    "Сведения о единоличном исполнительном органе – управляющей компании",
    "СНИЛС",
    "Сведения о доверенности",
    "Сведения о доверителе (доверителях) первоначальной доверенности",
    "Сведения о доверителе (доверителях)",
    "Сведения о законном представителе физического лица / Сведения о "
    "рукоприкладчике",
    "Сведения о единоличном исполнительном органе - индивидуальном "
    "предпринимателе",
    "Сведения об иностранном юридическом лице / Сведения о филиале "
    "(аккредитованном представительстве) иностранного юридического лица",
    "Сведения о нотариусе, совершившем нотариальное действие",
    "Сведения о нотариальном удостоверении",
    "Сведения о первоначальной доверенности",
    "Сведения о доверенности",
    "Сведения о лице (лицах), передавшем (передавших) полномочия",
    "Сведения о доверенности, на основании которой осуществляется передоверие",
    "Сведения о передаваемом (передаваемых) полномочии (полномочиях)",
    "Сведения о лице (лицах), получившем (получивших) полномочия",
    "Сведения о юридическом лице",
    "Сведения о руководителе иностранного юридического лица / Сведения о "
    "руководителе филиала (аккредитованного представительства) иностранного "
    "юридического лица",
    "Сведения о руководителе филиала (обособленном подразделении) юридического "
    "лица",
    "Сведения об удостоверении документа",
    "Сведения о представителе (представителях)",
    "Сведения о единоличном исполнительном органе - физическом лице",
    "Сведения о филиале (обособленном подразделении) юридического лица",
    "Сведения о юридическом лице",
    "Сведения о филиале (аккредитованном представительстве) иностранного "
    "юридического лица",
    "Сведения об индивидуальном предпринимателе",
    "Сведения о юридическом лице",
    "Сведения о рукоприкладчике",
    "Сведения об информационной системе, которая предоставляет техническую "
    "возможность получения информации о доверенности, досрочном прекращении "
    "действия доверенности, в том числе в силу ее отмены доверителем",
    "Сведения о физическом лице",
    "Сведения о физическом лице",
    "Сведения о филиале (обособленном подразделении) юридического лица",
    "Серия и номер документа",
    "Срок действия доверенности",
    "Статус участника нотариального действия",
    "Страна регистрации (инкорпорации)",
    "Текстовое значение для ограничения",
    "Текстовое содержание полномочия",
    "Тип доверителя",
    "Тип лица, передавшего полномочия",
    "Тип полномочия",
    "Тип представителя",
    "Сведения о документе, удостоверяющем личность физического лица",
    "Сведения об уплате за совершение нотариального действия",
    "Условие отзыва безотзывной доверенности",
    "ФИАС адрес в Российской Федерации",
    "ФИО доверителя (или представителя)",
    "ФИО ВРИО нотариуса",
    "ФИО нотариуса",
    "ФИО лица, подписавшего доверенность",
    "Сведения о физическом лице",
    "Сведения о физическом лице",
    "Фамилия",
    "Сведения о филиале (обособленном подразделении) юридического лица",
    "Форма доверенности",
    "Хеш PDF документа",
    "Хеш подписи",
};
constexpr std::array<std::string_view, 174> eng_expl{
    "External identifier of the ESIA object",
    "The expiration date of the identity document",
    "Address of the place of residence",
    "Address (location) on the territory of the Russian Federation",
    "Address in the Russian Federation",
    "The address of the legal entity / branch (separate subdivision) of the "
    "legal entity in the Russian Federation",
    "The address of the legal entity in the territory of the state in which it "
    "is registered",
    "Email address",
    "Information about an irrevocable power of attorney",
    "Format version",
    "Type of power of attorney",
    "The internal number of the power of attorney",
    "The internal number of the power of attorney on the basis of which the "
    "transfer is carried out",
    "The internal number of the original power of attorney",
    "ACTING notary",
    "Name of the authority that issued the document",
    "Citizenship",
    "Date of internal registration of the power of attorney",
    "Date and time of signature",
    "Date of issue of the document",
    "Date of the power of attorney (issue)",
    "Date of issue of the document",
    "Date of birth",
    "Attorney",
    "Information about the power of attorney",
    "Information about the principal",
    "Information about the principal of the original power of attorney",
    "The document confirming the incapacity of the principal",
    "A document confirming the authority of a person acting without a power of "
    "attorney",
    "Composition and structure of the document",
    "Post",
    "Additional ID of the power of attorney",
    "Additional information",
    "The method of issuing an electronic notary document",
    "Another way of issuing",
    "The sole executive body is an individual entrepreneur",
    "The management company acts as the sole executive body.",
    "The sole executive body is an individual",
    "INN of an individual",
    "INN of a foreign legal entity / branch (accredited representative office) "
    "of a foreign legal entity",
    "Information about an individual entrepreneur",
    "Information about an individual entrepreneur",
    "Ordinal number of the restriction",
    "FIAS Address ID",
    "File ID",
    "ID of the file for representing interests with the tax authority",
    "Name",
    "Information about a foreign legal entity",
    "Information about the branch (accredited representative office) of a "
    "foreign legal entity",
    "Other information of the identification label",
    "Other information",
    "The code of the CND form",
    "CHECKPOINT of a branch (accredited representative office) of a foreign "
    "legal entity",
    "Name of the authority that issued the document",
    "Document type code",
    "The code of the subdivision of the authority that issued the document",
    "The value code for the restriction",
    "The code of the tax authority to which the power of attorney is submitted",
    "The code of the tax authority in respect of which the power of attorney "
    "is valid",
    "The taxpayer's code in the country of registration (incorporation) or its "
    "equivalent",
    "Restriction code",
    "Authorization code",
    "Contact phone number",
    "Information about the person(s) acting on behalf of a legal entity "
    "without a power of attorney",
    "The benefit granted for the amount of",
    "Information about a machine-readable authorization (machine-readable "
    "credentials)",
    "The place of the power of attorney",
    "Place of birth",
    "Mnemonics of authority",
    "Number of the accreditation record",
    "Name of the document",
    "Name of the value for the restriction",
    "Name of the foreign legal entity / branch (accredited representative "
    "office) of the foreign legal entity",
    "Name of the individual entrepreneur",
    "Name of the restriction",
    "Name of the legal entity / Name of the branch (separate subdivision) of "
    "the legal entity",
    "Name of the authority",
    "Name of the registering authority",
    "Name of the constituent document",
    "Sending the generated electronic document to the principal's personal "
    "account on the EPSU website",
    "Sending the generated electronic document to the applicant's personal "
    "account on the FNP website",
    "Sending the generated electronic document to the attorney's office on the "
    "EPGU website",
    "Sending the generated electronic document to the attorney's personal "
    "account on the FNP website",
    "Single registration number of the power of attorney",
    "The single registration number of the power of attorney on the basis of "
    "which the transfer is carried out",
    "Single registration number of the original power of attorney",
    "The entry number of the unified population register",
    "The registration number of the power of attorney in the register of "
    "notarial acts, on the basis of which the transfer of power of attorney is "
    "carried out",
    "The registration number of the power of attorney in the register of "
    "notarial acts",
    "The registration number of the original power of attorney in the register "
    "of notarial acts",
    "OGRN",
    "OGRNIP",
    "Information about the restriction (restrictions) on the authority",
    "Description of the condition for revocation of an irrevocable power of "
    "attorney",
    "Patronymic (if any)",
    "Information about the person who delegated the authority",
    "Retrust",
    "Signature Image",
    "Handwritten signature",
    "Gender of the individual",
    "Type of powers of the sole executive body",
    "A sign of citizenship",
    "A sign of the principal's full civil legal capacity",
    "The power of attorney attribute",
    "A sign of a power of attorney issued by way of transfer",
    "A sign of a handshake",
    "A sign of transfer of an irrevocable power of attorney",
    "Indication of the possibility of making a transfer",
    "A sign of joint exercise of authority",
    "A sign of loss of authority during a transfer of trust",
    "The mandatory element flag",
    "Information about the representative",
    "The registration number of the person who passed the qualification exam "
    "at the Ministry of Justice",
    "Registration number in the country of registration (incorporation)",
    "Subject of the Russian Federation",
    "Information about the legal entity",
    "Information about the legal entity",
    "Information about the sole executive body – the management company",
    "SNILS",
    "Information about the power of attorney",
    "Information about the principal(s) of the original power of attorney",
    "Information about the principal(s)",
    "Information about the legal representative of an individual / Information "
    "about the handyman",
    "Information about the sole executive body - an individual entrepreneur",
    "Information about a foreign legal entity / Information about the branch "
    "(accredited representative office) of a foreign legal entity",
    "Information about the notary who performed the notarial act",
    "Information about the notarization",
    "Information about the original power of attorney",
    "Information about the power of attorney",
    "Information about the person(s) who transferred the powers",
    "Information about the power of attorney on the basis of which the "
    "transfer is carried out",
    "Information about the delegated authority(s)",
    "Information about the person(s) who received the authority",
    "Information about the legal entity",
    "Information about the head of a foreign legal entity / Information about "
    "the head of a branch (accredited representative office) of a foreign "
    "legal entity",
    "Information about the head of a branch (separate subdivision) of a legal "
    "entity",
    "Information about the document identification",
    "Information about the representative(s)",
    "Information about the sole executive body - an individual",
    "Information about a branch (separate subdivision) of a legal entity",
    "Information about the legal entity",
    "Information about the branch (accredited representative office) of a "
    "foreign legal entity",
    "Information about an individual entrepreneur",
    "Information about the legal entity",
    "Information about the hand handler",
    "Information about the information system that provides the technical "
    "possibility of obtaining information about the power of attorney, the "
    "early termination of the power of attorney, including by virtue of its "
    "cancellation by the principal",
    "Information about an individual",
    "Information about an individual",
    "Information about a branch (separate subdivision) of a legal entity",
    "Document series and number",
    "Validity period of the power of attorney",
    "The status of the participant of the notarial action",
    "Country of registration (incorporation)",
    "The text value for the restriction",
    "Text content of the authority",
    "Type of trustee",
    "The type of person who delegated the authority",
    "Type of authority",
    "Type of representative",
    "Information about the identity document of an individual",
    "Information about the payment for the commission of a notarial act",
    "The condition for revoking an irrevocable power of attorney",
    "FIAS address in the Russian Federation",
    "Full name of the principal (or representative)",
    "FULL NAME of the ACTING notary",
    "Notary's full name",
    "Full name of the person who signed the power of attorney",
    "Information about an individual",
    "Information about an individual",
    "Surname",
    "Information about a branch (separate subdivision) of a legal entity",
    "Power of Attorney form",
    "Hash of the PDF document",
    "Hash signatures",
};

SurguchTranslator::SurguchTranslator(QObject *parent) : QObject{parent} {}

QString SurguchTranslator::surguchTranslate(const QString &str) const {
    for (std::size_t i = 0; i < tag_names.size(); ++i) {
        if (QString::fromUtf8(tag_names[i].data(), tag_names[i].size()) ==
            str) {
            if (QLocale::system().language() == QLocale::Russian) {
                return QString::fromUtf8(rus_expl[i].data());
            }
            return QString::fromUtf8(eng_expl[i].data());
        }
    }
    return str;
}

}  // namespace core
